#!/bin/bash
# install.sh — SFTPGo plugin setup.
#
# Called by freeholdy in two phases for compose plugins:
#
#   Phase "pre"  (synchronous, before docker compose up):
#     Generates admin credentials and appends them to ${PROJECT_DIR}/.env so
#     docker compose can substitute SFTPGO_DEFAULT_ADMIN_* on first container start.
#
#   Phase "post" (background thread, after docker compose up is launched):
#     Waits for the REST API to be ready, creates the SFTP user, and saves
#     all credentials to /etc/sftpgo-credentials (mode 600).
#
# Environment variables provided by freeholdy:
#   PLUGIN_DIR                 — this plugin's source directory
#   PROJECT_DIR                — compose project directory (contains .env, compose files)
#   PROJECT_NAME               — project name (e.g. "sftpgo")
#   PROJECTS_DIR               — absolute path to freeholdy's unified projects/ directory
#   DOCKERFILES_DIR            — legacy alias kept for backward compatibility
#   BASE_DOMAIN                — e.g. "cloudopen.space"
#   SERVICE_SFTPGO_LOCAL_PORT  — loopback port allocated for nginx → WebClient

set -euo pipefail

PHASE="${1:-post}"

_gen_pass() {
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24
}

# ── Pre phase ──────────────────────────────────────────────────────────────────
if [[ "$PHASE" == "pre" ]]; then
    ADMIN_USER="admin"
    ADMIN_PASS="$(_gen_pass)"
    printf 'SFTPGO_ADMIN_USER=%s\nSFTPGO_ADMIN_PASS=%s\n' "$ADMIN_USER" "$ADMIN_PASS" \
        >> "${PROJECT_DIR}/.env"
    echo "sftpgo: admin credentials written to .env"
    exit 0
fi

# ── Post phase ─────────────────────────────────────────────────────────────────

# Load the credentials that the pre phase wrote (and the base .env values).
# shellcheck source=/dev/null
set -a; source "${PROJECT_DIR}/.env"; set +a

LOCAL_PORT="${SERVICE_SFTPGO_LOCAL_PORT}"
API="http://127.0.0.1:${LOCAL_PORT}/api/v2"
SFTP_USER="freeholdy"
SFTP_PASS="$(_gen_pass)"
CREDS_FILE="/etc/sftpgo-credentials"

# Wait for REST API (up to 120 s — image pull + container start can be slow).
echo "sftpgo: waiting for REST API on port ${LOCAL_PORT}…"
MAX_WAIT=120
WAITED=0
until curl -sf "${API}/version" >/dev/null 2>&1; do
    if [[ $WAITED -ge $MAX_WAIT ]]; then
        echo "sftpgo: API did not become ready after ${MAX_WAIT}s. Check: docker logs freeholdy_${PROJECT_NAME}_sftpgo" >&2
        exit 1
    fi
    sleep 2
    WAITED=$(( WAITED + 2 ))
done
echo "sftpgo: REST API ready after ${WAITED}s"

# Obtain JWT.
TOKEN_RESPONSE=$(curl -sf -X GET "${API}/token" \
    -u "${SFTPGO_ADMIN_USER}:${SFTPGO_ADMIN_PASS}" \
    -H "Content-Type: application/json")
JWT=$(echo "$TOKEN_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['access_token'])")
if [[ -z "$JWT" ]]; then
    echo "sftpgo: failed to obtain JWT — check admin credentials in ${PROJECT_DIR}/.env" >&2
    exit 1
fi

AUTH="Authorization: Bearer ${JWT}"

# Create SFTP user (skip if already exists).
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "$AUTH" "${API}/users/${SFTP_USER}")

if [[ "$HTTP_STATUS" == "200" ]]; then
    echo "sftpgo: user '${SFTP_USER}' already exists — skipping creation"
else
    USER_PAYLOAD=$(python3 -c "
import json, sys
print(json.dumps({
    'username':    '${SFTP_USER}',
    'password':    '${SFTP_PASS}',
    'home_dir':    '/srv/projects',
    'status':      1,
    'permissions': {'/': ['*']}
}))
")
    curl -sf -X POST "${API}/users" \
        -H "$AUTH" \
        -H "Content-Type: application/json" \
        -d "$USER_PAYLOAD" >/dev/null
    echo "sftpgo: user '${SFTP_USER}' created with home /srv/projects"
fi

# Save credentials (root-readable only).
cat > "$CREDS_FILE" << CREDS
# SFTPGo credentials — generated by the sftpgo plugin install.sh
# Keep this file secret: chmod 600 $CREDS_FILE

SFTPGO_ADMIN_USER=${SFTPGO_ADMIN_USER}
SFTPGO_ADMIN_PASS=${SFTPGO_ADMIN_PASS}

SFTP_HOST=${BASE_DOMAIN}
SFTP_PORT=2022
SFTP_USER=${SFTP_USER}
SFTP_PASS=${SFTP_PASS}
CREDS
chmod 600 "$CREDS_FILE"
echo "sftpgo: credentials saved to ${CREDS_FILE}"

# Patch cli/.env if it exists alongside the freeholdy repo root.
CLI_ENV="$(dirname "${PROJECT_DIR}")/../cli/.env"
if [[ -f "$CLI_ENV" ]]; then
    sed -i '/^SFTP_USER=/d; /^SFTP_PASSWORD=/d' "$CLI_ENV"
    printf 'SFTP_USER=%s\nSFTP_PASSWORD=%s\n' "$SFTP_USER" "$SFTP_PASS" >> "$CLI_ENV"
    echo "sftpgo: cli/.env updated"
fi

echo ""
echo "━━━  SFTPGo plugin setup complete  ━━━"
echo "  Admin:  https://files.${BASE_DOMAIN}/web/admin  (user: ${SFTPGO_ADMIN_USER})"
echo "  SFTP:   ${BASE_DOMAIN}:2022  (user: ${SFTP_USER})"
echo "  Credentials: ${CREDS_FILE}"
